# image: node:10.16.3

# cache:
#   paths:
#     - node_modules/

# before_script:
#   - npm install

# pages:
#   stage: deploy
#   script:
#     - CI=true npm run build
#     - rm -rf public
#     - mv build public
#     artifacts:
#       paths:
#         - public

#     only:
#       - staging

image: node:8.11.3 # can be upgraded, depending on your node version used
variables: isEnvProductionProfile:true
pages:
  stage: deploy
  script:
    - echo isEnvProductionProfile
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - staging # or master, the branch you want to publish
