export const SIMPLE_ACTION = "SIMPLE_ACTION";
export const AUTHENTICATION = "AUHENTICATION";
export const POST_REQUEST = "POST_REQUEST";
export const PUT_REQUEST = "PUT_REQUEST";
export const DELETE_REQUEST = "DELETE_REQUEST";